from get_music.kugou import kugou
from get_music import download
from get_music.migu import migu
from get_music.kuwo import kuwo
from get_music.netease import netease
from get_music.qq import qq
from get_music.oneting import oneting
from get_music.fivesing import fivesing
from get_music.baidu import baidu
