from get_music import kugou
from get_music import download
from get_music import migu
from get_music import kuwo
from get_music import netease
from get_music import qq
from get_music import oneting
from get_music import fivesing
from get_music import baidu
